# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherAppVer2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.0'
pod "SwiftyJSON"

  # Pods for WeatherAppVer2

end
